### ISSUE TITLE
Custom Selection Shows Blank on iOS (Sample App)

### ISSUE THREAD

**Issue by jfversluis** [ME-MarvinE/XCalendar#5] opened 2022-01-31 10:10 UTC
If I use the custom selection template for dates the dates will go blank when I select something. On Android I see a red circle. Reporting this for the sample app, but there might be a deeper problem here where this functionality is not working correctly for iOS

![image](https://user-images.githubusercontent.com/939291/151774968-97d91e66-fbba-4b5c-a706-9c0cabfda240.png)

**Comment by ME-MarvinE** [comment] 2022-02-07 12:43
Could you check if this is fixed in 2.0.1?  
  
Could you also post the code for the template you're trying to set?

**Comment by jfversluis** [comment] 2022-02-08 19:53
Downloaded the latest code and sample app, still happens

https://user-images.githubusercontent.com/939291/153064972-21ca4ea4-3175-4792-870f-5d77fb6f7848.mov

**Comment by ME-MarvinE** [comment] 2022-02-09 04:51
I can't test anything on IOS myself so I'm just going to suggest places to look/test if anyone decides to help.  

The only code that is executed when a day is selected is below in `CalendarDayView`'s `UpdateView` method:
```C#
else if (IsSelected && IsCurrentMonth)
{
    BackgroundColor = SelectedBackgroundColor;
    BorderColor = SelectedBorderColor;
    TextColor = SelectedTextColor;
}
```
These values could be hardcoded to test if something is going wrong with bindings somewhere.  
  
Something else that might be causing the issue is the trigger for a TouchEffect used in the MonthView's default implementation:
```XAML
<MultiTrigger TargetType="{x:Type xc:CalendarDayView}">
        <MultiTrigger.Conditions>
                <BindingCondition Binding="{Binding SelectionType, Source={x:Reference MainCalendarView}, Converter={StaticResource EnumToBoolConverter}, ConverterParameter={x:Static Enums:SelectionType.None}}" Value="False" />
                <BindingCondition Binding="{Binding IsCurrentMonth, Source={RelativeSource Self}}" Value="True" />
                <BindingCondition Binding="{Binding IsOutOfRange, Source={RelativeSource Self}}" Value="False" />
        </MultiTrigger.Conditions>
        <Setter Property="xct:TouchEffect.NativeAnimation" Value="True" />
        <Setter Property="xct:TouchEffect.Command" Value="{Binding ChangeDateSelectionCommand, Source={x:Reference MainCalendarView}}" />
        <Setter Property="xct:TouchEffect.CommandParameter" Value="{Binding DateTime, Source={RelativeSource Self}}" />
</MultiTrigger>
```
This could be tested by replacing it with a `TapGestureRecognizer` or setting the values without using a trigger.

If none of these work, testing and changing the `IsSelected` and `IsCurrentMonth` values in the following code may give some info.
```XAML
<CalendarDayView DateTime="2/09/2022" IsSelected="True" IsCurrentMonth="True" IsOutOfRange="False" IsToday="False">
```

**Comment by ME-MarvinE** [comment] 2022-07-26 14:59
Hi @jfversluis, can you check if this is fixed in the latest version of XCalendar.Forms?

**Comment by jfversluis** [comment] 2022-07-26 19:18
Still happens unfortunately with the code on dev. I've stepped through it, the values seem to come through alright. The interesting thing is, when I set it to landscap it does suddenly show.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/939291/181093461-ce1b339e-4607-4193-a765-af8fc270acab.png">

**Comment by jfversluis** [comment] 2022-07-26 19:23
It has to do with the CornerRadius. At runtime the Width is 45, Height is 50 and the CornerRadius is 100 which makes it disappear entirely.

**Comment by ME-MarvinE** [comment] 2022-07-26 19:27
Ohh okay. I will remove the cornerradius 100 in the future and replace it with workarounds.

I am planning to remove the 'FramedLabel' (Forms) and 'BorderedLabel' (MAUI) controls anyway though. No need to slow down the Calendar when the user may not even want a border at all. If they do, they can easily add it through the template.

**Comment by jfversluis** [comment] 2022-07-26 19:28
I don't think it just has to do with the border. If you remove the CornerRadius entirely it will always be a square when people might want it to be round? But up to you how to fix it :)

**Comment by ME-MarvinE** [comment] 2022-07-26 19:33
* Currently `CalendarDayView` inherits from `FramedLabel` which is a `Label` inside a `Frame`.
* I want to make it so CalendarDayView inherits directly from `Label`.
* The user will be able to use the `DayTemplate` property to add a `Frame` if they want to make it round or have a border.

Hope it makes sense and thanks for your help! I may buy an older iphone to debug with if there are a lot of people using XCalendar on IOS. Until then, it may stay an issue for a few more months.

**Comment by ME-MarvinE** [comment] 2022-10-14 00:07
The issue is no longer applicable as the custom switch was removed from the sample app.

Hopefully it was just a querk from how it was implemented in the sample app and not an issue to do with the plugin itself. We'll just have to wait and see if an issue arises with a similar description.

**Closed by ME-MarvinE** 2022-10-14 00:07 UTC
Labels: bug, help wanted, ios
