### ISSUE TITLE
XCalendar.Maui 4.4.2 works when debugging, crashes at startup when installed on android phone

### ISSUE THREAD

**Issue by EugenM88** [ME-MarvinE/XCalendar#136] opened 2023-05-22 19:29 UTC
Greetings!

After successfully implementing this amazing control and trying to test it on my phone (Realme 8 Pro with Android 13)
The program crashes at startup after installation.

The program works just fine in the emulator when debugging, but when changing to release and trying to manually install the app into my android phone, the program installs fine, however when starting the program up, the .net maui splashscreen appears and then app instantly crashes without any error.

I have tried using a clean project from scratch, same problem persists.
Is there any tip or anything i could do to make it run on a android phone?

Devices and OS Versions:
Realme 8 Pro:
Android 13:
Windows Version: 11 Pro, 22h2 (custom built pc)
Visual Studio 2022 17.6.1 .NET 7

Thanks in advance for all your help!

**Comment by ME-MarvinE** [comment] 2023-05-22 23:59
May be related to #67.

* What device are you using in your emulator?
* What happens when you try to run the MAUI app on your Windows Machine (Debug and Release)?
* What code did you have in your clean project from scratch?
* Are you able to run your project on your Android device in debug mode instead of release mode?
* Are you able to run your project if you remove the use of any XCalendar controls such as CalendarView or MonthView?
* Are you able to run a file new MAUI app without XCalendar on your Android device (Debug and Release)?
* Are you able to run a file new MAUI app with XCalendar.MAUI but not using any controls from it on your Android Device (Debug and Release)?
* Are you able to run the sample app on your Android device (Debug and Release)?

**Comment by EugenM88** [comment] 2023-05-23 09:54
Greetings, to make this debugging easier, i have uploaded a test project to a zip file on wetransfer.
[You can find it here by clicking this link](https://wetransfer.com/downloads/ab395a60fea960335dd082c8ecde01ed20230523090444/0f0931bfdfcd36b6544dc8184e505a2f20230523090458/b19218?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)

As to reply to your questions
1) The device in the emulator is the default android device (Pixel 5 API 33 i think this is the default)
2) I never tried to run in Windows Machine as i need to change some code behind to be able to do so, i only used the android emulator to debug and a physical Realme 8 Pro device to test when released.
3) The code i had from scratch was just the default .net Maui Code + the xcalendar code, a few more lines in the csproj file to accomodate a key to publish the .apk file, a models folder with a model.cs class inside where the xcalendar has its binded data and thats about it.
4) I have never tried it in debug, i tought you werent able to do so in .net Maui as it wont even install if i try as it says its not compatible with my phone.
5 and 6) Once i add the XCalendar to the project, even after removing it from said project by removing all the lines of codes and uninstalling the nuget package, still, i can no longer run the published apk.
7) Yes as long as i do not ever reference XCalendar i am able to run the released apk (debug is not compatible with my arm device).
8) No.
9) I have never tried it as i couldnt build the sample Xcalendar app.

NOTE: This information might be important, in order to sign the apk, i use the terminal with the following guide:
In terminal VS2022

`keytool -genkey -v -keystore key.keystore -alias ProjectAlias -keyalg RSA -keysize 2048 -validity 10000`
Password: passwordsomething153
FirstName Eugen
LastName Systems

In MainProject programming class (example open file explorer go inside project folder and find NewMauiApp1.csproj), add before last </Project> line
	<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningKeyStore>key.keystore</AndroidSigningKeyStore>
		<AndroidSigningStorePass>passwordsomething153</AndroidSigningStorePass>
		<AndroidSigningKeyAlias>ProjectAlias</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>passwordsomething153</AndroidSigningKeyPass>
	</PropertyGroup>


Please dont hesitate to contact me for further details as i am very new to .net MAUI and this is actually my very first .net MAUI project that im trying to build.

Best Regards!

**Comment by ME-MarvinE** [comment] 2023-05-23 23:27
I am able to run your project in debug mode but not release mode. In release mode I get these errors:
![image](https://github.com/ME-MarvinE/XCalendar/assets/73718829/fa9549f7-ffc0-4148-9fc8-1e7ffdfc62c9)

They don't seem to be related to XCalendar but I have yet to do actual testing by removing XCalendar from the project etc.

I've only ever signed APK and provided keystore details in Xamarin but in MAUI it seems to be the same: Project (NetMauiApp1) -> Properties -> Android -> Package Signing and then right clicking Project (NetMauiApp1) and clicking "publish" and then selecting the resulting archive and clicking "Distribute" and entering the keystore details there.

I've never seen someone experiencing your answer to Q4. It may provide insight into why your app crashes in release. What is the exact error message that says it isn't compatible with your phone? If it's your app that isn't compatible then it would make sense it doesn't work in release, but if debugging isn't compatible then that needs to be troubleshooted as to why. I just don't see how debugging wouldn't be supported on a standard Android 13 device. I assume you have the developer options enabled and the "USB Debugging" setting enabled. I see the Release package format is set to "Bundle" instead of "Apk" in the project so I don't even know how an APK would be genereated.

For your answer to Q3, could you create a new project and not include the code to do with publishing and see if it works first, then add the publishing details to see if that is causing yor issue. 

I have no experience with using the terminal to sign the apk. It seems like you're generating an APK and installing it manually on your Android device, which is where you would get the "App is incompatible" error. The app should automatically be deployed onto your device whether in debug or release and you shouldn't have to manually do anything other than open the resulting app. If you install the app manually on your device then it makes sense why it would work in the emulator but not in your physical device. When you generate your APK how do you actually get it to your device? Could you provide steps if it isn't just: Run in release -> Go to Android device -> run app?

~~Im unable to understand your answer to Q5 ad Q6~~

>     4. I have never tried it in debug, i tought you werent able to do so in .net Maui as it wont even install if i try as it says its not compatible with my phone.
>        5 and 6) Once i add the XCalendar to the project, even after removing it from said project by removing all the lines of codes and uninstalling the nuget package, still, i can no longer run the published apk.
> 
>     5. Yes as long as i do not ever reference XCalendar I am able to run the released apk (debug is not compatible with my arm device).
> 
>     6. No.

~~Your answer to Q4 where it says "5 and 6)" seems to contradict your answer to Q5. I understand that you created a new project which worked initially. Then you added XCalendar and then removed it and it never worked afterwards. I've never seen this before either. What happens when you add and remove other nuget packages that add MAUI controls? Can you try at least 2 others one at a time and see if you get the same result?~~ I think I see that Q4 "5 and 6)" refers to Q5 and Q6 and then your answers to Q5, Q6, and Q7 are actually your aswers to Q7, Q8, and Q9.

From what I've seen I think this issue is caused by how you build and deploy your app to your device rather than by XCalendar, but it is weird that installing it and removing it permanently stops your app from running. Does this happen if you install other packages that add MAUI controls?

**Comment by EugenM88** [comment] 2023-05-24 15:18
Sorry for the confusion with the point numbering there....
For some reason github changes the numbers automatically of each point, go figure.


I can "publish" an apk without using any key or any commands from the terminal but then it wont be compatible with my phone as the apk is not published "properly".
It's probably because the android emulator is running in a x86 cpu and my phone is actually arm.

What i wanted to achieve was actually very simple, i want to make an .apk file that i can manually copy to my phone internal storage and then the user installs said apk from its mobile phone internal memory (Not Google Play Store).
I do not intend to debug the app with adb, or debug it directly from visual studio, i want to check how the app actually behaves when published and installed in a non dev phone, which is where it actually crashes after xecalendar is referenced.

All tutorials i've found online shows me that i must sign the android apk with the keytool in order for me to actually be able to generate a proper apk that can install and run in any phone.

Is there perhaps something wrong with my process or maybe im missing something?

**Comment by ME-MarvinE** [comment] 2023-05-24 16:13
I don't know the difference between ARM and the architecure of your emulator and its implications. What do you mean it's not compatible with your phone? At what point do you get a warning or error when you don't publish the app using your method?

Have you tried the below method for generating a signed apk? I think it's an alternative to using the terminal.
> I have no experience with using the terminal to sign the apk. I've only ever signed APK and provided keystore details in Xamarin but in MAUI it seems to be the same: Project (NetMauiApp1) -> Properties -> Android -> Package Signing and then right clicking Project (NetMauiApp1) and clicking "publish" and then selecting the resulting archive and clicking "Distribute" and entering the keystore details there.

What result did you get from this:
> it is weird that installing it and removing it will permanently stop your app from running. Does this happen if you install other packages that add MAUI controls?

As far as I'm aware and in my experience you don't need to sign an apk to have it run on devices. I don't know why it doesn't let you install the app on your device. There are some security/developer settings such as "Install from unknown sources" which could prevent the user from installing your app though. I'm out of ideas as to what it could be.

 In regards to:
> Is there perhaps something wrong with my process or maybe im missing something?

I'm out of ideas and can only suggest to try with other packages or with other sample apps on GitHub to see if your apk-signing process works with them. If they do, then its an issue with XCalendar and I don't know why it would cause crashing after its been removed from the project. Maybe you could try to find someone else with a similar issue with their MAUI app, or raise an issue in the MAUI repo to get help from people with more knowledge of the Android OS and MAUI framework.

I would suggest [Syncfusion's Calendar](https://help.syncfusion.com/maui/calendar/getting-started) as an alternative since I don't think this issue will be solved anytime soon.

**Comment by EugenM88** [comment] 2023-05-25 14:32
Im not sure if this is of any interest as im not even sure if it's actually accurate information, but, perhaps .net maui no longer uses relaycommands and probably replaced it with something newer?

Again i have really no experience with .net maui and this is my first ever project with it, so take this specific info with a grain of salt.

**Comment by ME-MarvinE** [comment] 2023-05-25 17:04
Will look at this again some time, great debugging

**Comment by ME-MarvinE** [comment] 2023-05-26 17:40
# Running first set of code
## Issue 1
![image](https://github.com/ME-MarvinE/XCalendar/assets/73718829/30ad27cd-6430-49a9-be61-bd7ca6e49fe5)
### Solution
Remove `Style="{StaticResource DefaultCalendarViewStyle}"` from
```xaml
            <xc:CalendarView
                Background="LightGray"
                x:Name="MainCalendarView"
                BackwardsArrowCommand="{Binding NavigateCalendarCommand}"
                Days="{Binding Calendar.Days}"
                DaysOfWeek="{Binding Calendar.DayNamesOrder}"
                ForwardsArrowCommand="{Binding NavigateCalendarCommand}"
                NavigatedDate="{Binding Calendar.NavigatedDate}"
                Style="{StaticResource DefaultCalendarViewStyle}">
```

## Issue 2
![image](https://github.com/ME-MarvinE/XCalendar/assets/73718829/9d89101e-bd77-41d1-9642-c46ca1c84100)
### Solution
Remove `Style="{StaticResource DefaultNavigationViewStyle}"` from
```xaml
                <xc:CalendarView.NavigationViewTemplate>
                    <ControlTemplate>
                        <xc:NavigationView
                            BackwardsArrowCommand="{Binding BackwardsArrowCommand, Source={RelativeSource TemplatedParent}}"
                            BackwardsArrowCommandParameter="{Binding BackwardsArrowCommandParameter, Source={RelativeSource TemplatedParent}}"
                            ForwardsArrowCommand="{Binding ForwardsArrowCommand, Source={RelativeSource TemplatedParent}}"
                            ForwardsArrowCommandParameter="{Binding ForwardsArrowCommandParameter, Source={RelativeSource TemplatedParent}}"
                            Style="{StaticResource DefaultNavigationViewStyle}"
                            Text="{Binding Text, Source={RelativeSource TemplatedParent}}"/>
                    </ControlTemplate>
                </xc:CalendarView.NavigationViewTemplate>
```

## Issue 3

The StaticResources "DefaultDayViewCurrentMonthStyle", "DefaultDayViewTodayStyle", and "DefaultDayViewSelectedStyle" are used in the following code but are not defined:
```xaml
                                <xc:DayView.CurrentMonthStyle>
                                    <Style BasedOn="{StaticResource DefaultDayViewCurrentMonthStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.CurrentMonthStyle>

                                <xc:DayView.TodayStyle>
                                    <Style BasedOn="{StaticResource DefaultDayViewTodayStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.TodayStyle>

                                <xc:DayView.SelectedStyle>
                                    <Style BasedOn="{StaticResource DefaultDayViewSelectedStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.SelectedStyle>
```

### Solution
Either don't set "BasedOn", or if you want to use the default look of the DayView, replace them with the values in the XCalendar.Maui.DefaultStyles class. For example:
```xaml
                                <xc:DayView.CurrentMonthStyle>
                                    <Style BasedOn="{x:Static xcStyles.DefaultStyles.DefaultDayViewCurrentMonthStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.CurrentMonthStyle>
```
Where `xcStyles` is defined earlier in the view:  `xmlns:xcStyles="clr-namespace:XCalendar.Maui.Styles;assembly=XCalendar.Maui"`

# Looking at second set of code:
Issues from your first set of code also apply and will not be ammended in the solutions provided.

## Issue 1
> It builds fine, works fine in emulator and even the published apk installs fine on the phone and displays without crashing!
Im not sure how to be able to change the months and arrows colors and select different dates using the new 4.5.1 calendar version with the working code, as of right now the working example doesnt allow the user to interact with the control at all.

You have defined the `DateSelectionCommand` but you have not assigned it to the days in your Calendar in XAML like you did in your first example. The day is being tapped but non of the states know that you want to use that command: 
```xaml
                                <xc:DayView.CurrentMonthStyle>
                                    <Style BasedOn="{StaticResource DefaultDayViewCurrentMonthStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.CurrentMonthStyle>

                                <xc:DayView.TodayStyle>
                                    <Style BasedOn="{StaticResource DefaultDayViewTodayStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.TodayStyle>

                                <xc:DayView.SelectedStyle>
                                    <Style BasedOn="{StaticResource DefaultDayViewSelectedStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.SelectedStyle>
### Solution

Set the DayTemplate to a DayView and define the style. Use BasedOn and the DefaultStyles class to inherit from the default styles used. The following code sets the command to use when a day is tapped and is in the `CurrentMonth` DayState. The XAML namespace for "xcStyles" is defined earlier in the view: `xmlns:xcStyles="clr-namespace:XCalendar.Maui.Styles;assembly=XCalendar.Maui"`. The page is given `x:Name="This"` so the page's BindingContext can be accessed inside the DataTemplate.
```xaml
                                <xc:DayView.CurrentMonthStyle>
                                    <Style BasedOn="{StaticResource DefaultDayViewCurrentMonthStyle}" TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.CurrentMonthStyle>
```

It really is valuable testing with a debugger first to see the errors that cause your app to crash. After that you can delete the app and test without the debugger like you do currently. With XAML there can be many runtime errors so I think its essential that you find out why you're not able to run apps in debug mode on your phone, especially if you're using complex templates and bindings. Are you able to run in debug mode in your emulator? 

You said it ran fine in the emulator. I don't know how that occurred either as it still should have crashed/thrown an exception because of the afformentioned issues.

Thanks for doing tests and posting what did and didn't work. Made it much easier to spot the difference.

**Comment by EugenM88** [comment] 2023-06-09 12:34
Hello, sorry for the delay i have been really busy these days and couldnt test your answear untill today.

Thank you very much for your reply, great news!
It semms to be working just fine now, it builds ok and no longer crashes on my phone when manually deployed and installed from an apk, however now im confused on how to get the last part working, namely i dont know where to put this code:

```
<xc:DayView.CurrentMonthStyle>
                                    <Style TargetType="{x:Type xc:DayView}">
                                        <Setter Property="Command" Value="{Binding BindingContext.ChangeDateSelectionCommand, Source={x:Reference This}}"/>
                                        <Setter Property="CommandParameter" Value="{Binding DateTime}"/>
                                    </Style>
                                </xc:DayView.CurrentMonthStyle>
```

Is there a chance you could help me out make this work on 4.5.1, example: to be able to change months and click on specific days?
I dont know why but im struggling really hard with the documentation, even though it should be as simple as a copy and paste.

Once more thank you for your time!

**Comment by ME-MarvinE** [comment] 2023-06-09 15:04
Stuff from the sample app is almost copy paste but at least a little knowledge is required to recognise what resources were used need to be removed or replicated in your app like Styles or x:Name or nuget packages. Things can also be done in many ways, and the way I have dine it may not always suite your needs.

Anyway, if you want to move the month and be able to select days, I recommend looking at the "Date Selection" example in the sample app.

The `<xc:DayView.CurrentMonthStyle>` would go in the `DataTemplate` that you put inside the `xc:CalendarView.DayTemplate>. This usage is present in many of the examples.

**Comment by ME-MarvinE** [comment] 2023-06-09 15:06
Stuff from the sample app is almost copy paste but at least a little knowledge is required to recognise what resources were used need to be removed or replicated in your app like Styles or x:Name or nuget packages. Things can also be done in many ways, and the way I have dine it may not always suite your needs.

Anyway, if you want to move the month and be able to select days, I recommend looking at the "Date Selection" example in the sample app.

The `<xc:DayView.CurrentMonthStyle>` would go in the `DataTemplate` that you put inside the `xc:CalendarView.DayTemplate>. This usage is present in many of the examples.

**Closed** 2024-01-23 18:48 UTC
Labels: bug
